### ISSUE TITLE
Publish versions to Maven Repository

### ISSUE THREAD

**Issue by DieterDePaepe** [hharrison/java3d-core#14]
The Maven2 central repository (see http://search.maven.org/#browse) has version 1.3.1 of Java3D.

Maven2 bundles of more recent versions should be built automatically and synced 
with the central repository, so that developers who use Java3D with Maven2 don't 
need to hunt down these jar files manually and download them.
Instructions for doing this are available at the following URL:
http://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by teil3** [comment]
I would really welcom this!

**Comment by gouessej** [comment]
I'm not opposed to this request for enhancement but Java3D must be updated to support JOGL 2.3.0 and later first. @io7m Maybe you can help, I'm not a Maven guru unlike you :)

**Comment by io7m** [comment]
On 2015-03-24T08:25:28 -0700
Julien Gouesse <notifications@github.com> wrote:

> I'm not opposed to this request for enhancement but Java3D must be updated to support JOGL 2.3.0 and later first. @io7m Maybe you can help, I'm not a Maven guru unlike you :)

I can certainly help.

What needs doing?

M

**Comment by ctrueden** [comment]
FWIW, I have Mavenized the `java3d-core`, `java3d-utils` and `vecmath` codebases here:
* https://github.com/hharrison/java3d-core/compare/master...ctrueden:maven
* https://github.com/hharrison/java3d-utils/compare/master...ctrueden:maven
* https://github.com/hharrison/vecmath/compare/master...ctrueden:maven

Of course, this would make it trivial to start publishing artifacts to a Maven repository.

**Comment by ctrueden** [comment]
I submitted some still-pending PRs to Mavenize the Java 3D components:

* hharrison/vecmath#5
* hharrison/java3d-core#19 (prerequisite to the Mavenization)
* hharrison/java3d-utils#2 (prerequisite to the Mavenization)

In the meantime, I have forked the Java 3D repositories to the SciJava organization:

* https://github.com/scijava/java3d-core
* https://github.com/scijava/java3d-utils
* https://github.com/scijava/vecmath

And stacked the Maven-related work on top of their respective master branches.

I then cut releases to Maven Central under `org.scijava` group ID with version `1.6.0-scijava-1`, so that people can start using this code from other Maven-compatible projects.

I do still hope we can get Java 3D officially converted to Maven—there are many advantages!

**Comment by gouessej** [comment]
I don't forget your suggestion but I'm a bit ill at ease as the Maven builds should be managed by the JogAmp community as "we" maintain it, we ensure that it goes on working with the latest version of JOGL (currently 2.3.2). To me, the fact that some people use your Maven builds in their own projects is rather a problem than a solution, it adds some confusion, it's not good, you could have used a separate Maven repository instead of using Maven Central so that you can use Maven with Java3D in ImageJ without confusing the end users by providing your own builds on Maven Central.

Keep in mind that we are a few contributors. If there is a problem with your builds, I fear that the developers will contact us. I understand that you're impatient to make everything work but this solution may cause much more problems than you imagine.

I advise you to use our official IRC channel, get in touch with Mark and Sven to push your builds on our Maven development repository, maybe make your pull requests against my repository instead of Harvey's repository if he is too busy to look at them right now so that we can go forward, approve your changes and make everything correctly. Your contributions are very welcome and thank you for your efforts.

Warning: Keep in mind that Java3D 1.6 won't evolve, we only maintain it, we fix the bugs, it will never support OpenGL ES, forward compatible contexts, ...

**Comment by gouessej** [comment]
I'll just check that I'm in sync with Harvey's changes before you can make your pull request against my repository.

**Comment by ctrueden** [comment]
It has been nearly 8 months since I first did the Mavenization. By now it is clear that the Java 3D project is not maintained in a timely manner. Which is fine—I know everyone is really busy, and I sympathize. But to reduce the pressure, I published the builds to Maven Central so the larger community at least has some way of consuming this awesome work using industry standard tools. I changed the groupId and version suffix to make it clear these are unofficial builds, as per Maven convention.

I fully appreciate that there is a support burden associated with these projects. It seems totally reasonable to tell them that JogAmp cannot support these unofficial builds, and point them to the SciJava project with their questions.

If you want me to file the PRs against a different repository, just let me know. Or feel free to pull the patches and do whatever you want with them. I'm here if you have questions.

> Warning: Keep in mind that Java3D 1.6 won't evolve, we only maintain it, we fix the bugs, it will never support OpenGL ES, forward compatible contexts, ...

Right. That's exactly why we need to just get the thing out the door, available for people to use as they transition to newer and better APIs...

**Comment by ctrueden** [comment]
Discussion thread [started on the JogAmp forum](http://forum.jogamp.org/Migrating-Java-3D-to-Maven-and-publishing-Maven-artifacts-td4035555.html).

**Comment by gouessej** [comment]
Concerning your very last sentence, it's difficult to find a replacement solution without knowing your needs and there are at least 2 other scenegraph APIs supporting JOGL and already more or less mavenized but both have pros and cons.

**Comment by gouessej** [comment]
@ctrueden Java3D 1.7.0 can already be built with Maven. Rather contact the maintainer on the official JogAmp forum if you need it to be on Maven Central. Several developers asked for it, it's going to be done for Java3D 1.7 but not for Java3D 1.6.

**Comment by gouessej** [comment]
@ctrueden There is no fork. @philjord has been working on Android support for Java 3D for years and is the maintainer. Anyway, the bugs and requests for enhancement must be reported in the JogAmp bug tracker rather than here.

I'm going to leave Github. The official repository of Java3D is here:
https://jogamp.org/cgit/java3d/

However, Java3D 1.7.0 hasn't been pushed into this repository yet.

Personally, I prefer using JogAmp Git Repositories in order to avoid depending on third party platforms especially when they get bought by Microsoft and its "friends".
